### This program will summarise the results from the simulation
rm(list=ls())

## Load image
load("R_out/multinom dl comparison scen1to5.RData")


### Create lists of dataframes of the simulations output
scen1.dataframes <- vector("list", 9)
for (i in 1:9){scen1.dataframes[[i]] <- data.frame(scenario1.res[[(i)]])}

scen2.dataframes <- vector("list", 9)
for (i in 1:9){scen2.dataframes[[i]] <- data.frame(scenario2.res[[(i)]])}

scen3.dataframes <- vector("list", 9)
for (i in 1:9){scen3.dataframes[[i]] <- data.frame(scenario3.res[[(i)]])}

scen4.dataframes <- vector("list", 8)
for (i in 1:8){scen4.dataframes[[i]] <- data.frame(scenario4.res[[(i)]])}

scen5.dataframes <- vector("list", 8)
for (i in 1:8){scen5.dataframes[[i]] <- data.frame(scenario5.res[[(i)]])}


### Give names to list elements### Scenario 1
names(scen1.dataframes) <- c(100,250,500,1000,540,564,576,572,606)
names(scen2.dataframes) <- c(100,250,500,1000,569,699,628,570,571)
names(scen3.dataframes) <- c(100,250,500,1000,565,714,582,565,566)
names(scen4.dataframes) <- c(250,500,1000,647,1105,901,813,1025)
names(scen5.dataframes) <- c(250,500,1000,706,1742,1457,1156,2003)


sample.sizes1 <- c(100,250,500,1000,540,564,576,572,606)
sample.sizes2 <- c(100,250,500,1000,569,699,628,570,571)
sample.sizes3 <- c(100,250,500,1000,565,714,582,565,566)
sample.sizes4 <- c(250,500,1000,647,1105,901,813,1025)
sample.sizes5 <- c(250,500,1000,706,1742,1457,1156,2003)


scen1.dataframes.S <- scen1.dataframes
scen2.dataframes.S <- scen2.dataframes
scen3.dataframes.S <- scen3.dataframes
scen4.dataframes.S <- scen4.dataframes
scen5.dataframes.S <- scen5.dataframes



### Calculate median of each entity of interest and put into a table
get.output.tables.slopes <- function(data.in){
  tables.out <- rbind(
    # First row
    round(c(quantile(data.in[[1]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[1]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[1]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[1]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Second row
    round(c(quantile(data.in[[2]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[2]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[2]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[2]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Third row
    round(c(quantile(data.in[[3]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[3]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[3]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[3]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Fourth row
    round(c(quantile(data.in[[4]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[4]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[4]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[4]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Fifth row
    round(c(quantile(data.in[[5]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[5]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[5]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[5]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Sixth row
    round(c(quantile(data.in[[6]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[6]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[6]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[6]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Seventh row
    round(c(quantile(data.in[[7]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[7]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[7]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[7]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3)
    )
    return(tables.out)}
      

### Repeat but for the tables that just have 6 rows
get.output.tables.slopes.i6 <- function(data.in){
  tables.out <- rbind(
    # First row
    round(c(quantile(data.in[[1]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[1]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[1]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[1]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Second row
    round(c(quantile(data.in[[2]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[2]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[2]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[2]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Third row
    round(c(quantile(data.in[[3]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[3]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[3]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[3]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Fourth row
    round(c(quantile(data.in[[4]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[4]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[4]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[4]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Fifth row
    round(c(quantile(data.in[[5]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[5]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[5]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[5]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3),
    # Sixth row
    round(c(quantile(data.in[[6]]$Slope.devel.m.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[6]]$Slope.devel.m.cali.m.2, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[6]]$Slope.devel.d.cali.m.1, probs = c(0.25,0.5,0.75)),
            quantile(data.in[[6]]$Slope.devel.d.cali.m.2, probs = c(0.25,0.5,0.75))),3)
  )
  return(tables.out)}

### And apply it to each set of results
output.scen1.slopes <- get.output.tables.slopes(scen1.dataframes.S)
output.scen2.slopes <- get.output.tables.slopes(scen2.dataframes.S)
output.scen3.slopes <- get.output.tables.slopes(scen3.dataframes.S)
output.scen4.slopes <- get.output.tables.slopes.i6(scen4.dataframes.S)
output.scen5.slopes <- get.output.tables.slopes.i6(scen5.dataframes.S)



### Calculate mean of each entity of interest and put into a table
get.output.tables.se.mean <- function(data.in){
  tables.out <- rbind(
    # First row
    round(c(mean(data.in[[1]]$se.m.1.1),
            mean(data.in[[1]]$se.m.1.2),
            mean(data.in[[1]]$se.m.1.3),
            mean(data.in[[1]]$se.m.1.4),
            mean(data.in[[1]]$se.m.1.5),
            mean(data.in[[1]]$se.m.1.6),
            mean(data.in[[1]]$se.m.2.1),
            mean(data.in[[1]]$se.m.2.2),
            mean(data.in[[1]]$se.m.2.3),
            mean(data.in[[1]]$se.m.2.4),
            mean(data.in[[1]]$se.m.2.5),
            mean(data.in[[1]]$se.m.2.6)),3),
    round(c(mean(data.in[[1]]$se.dl.1.1),
            mean(data.in[[1]]$se.dl.1.2),
            mean(data.in[[1]]$se.dl.1.3),
            mean(data.in[[1]]$se.dl.1.4),
            mean(data.in[[1]]$se.dl.1.5),
            mean(data.in[[1]]$se.dl.1.6),
            mean(data.in[[1]]$se.dl.2.1),
            mean(data.in[[1]]$se.dl.2.2),
            mean(data.in[[1]]$se.dl.2.3),
            mean(data.in[[1]]$se.dl.2.4),
            mean(data.in[[1]]$se.dl.2.5),
            mean(data.in[[1]]$se.dl.2.6)),3),
    # Second row
    round(c(mean(data.in[[2]]$se.m.1.1),
            mean(data.in[[2]]$se.m.1.2),
            mean(data.in[[2]]$se.m.1.3),
            mean(data.in[[2]]$se.m.1.4),
            mean(data.in[[2]]$se.m.1.5),
            mean(data.in[[2]]$se.m.1.6),
            mean(data.in[[2]]$se.m.2.1),
            mean(data.in[[2]]$se.m.2.2),
            mean(data.in[[2]]$se.m.2.3),
            mean(data.in[[2]]$se.m.2.4),
            mean(data.in[[2]]$se.m.2.5),
            mean(data.in[[2]]$se.m.2.6)),3),
    round(c(mean(data.in[[2]]$se.dl.1.1),
            mean(data.in[[2]]$se.dl.1.2),
            mean(data.in[[2]]$se.dl.1.3),
            mean(data.in[[2]]$se.dl.1.4),
            mean(data.in[[2]]$se.dl.1.5),
            mean(data.in[[2]]$se.dl.1.6),
            mean(data.in[[2]]$se.dl.2.1),
            mean(data.in[[2]]$se.dl.2.2),
            mean(data.in[[2]]$se.dl.2.3),
            mean(data.in[[2]]$se.dl.2.4),
            mean(data.in[[2]]$se.dl.2.5),
            mean(data.in[[2]]$se.dl.2.6)),3),
    # Third row
    round(c(mean(data.in[[3]]$se.m.1.1),
            mean(data.in[[3]]$se.m.1.2),
            mean(data.in[[3]]$se.m.1.3),
            mean(data.in[[3]]$se.m.1.4),
            mean(data.in[[3]]$se.m.1.5),
            mean(data.in[[3]]$se.m.1.6),
            mean(data.in[[3]]$se.m.2.1),
            mean(data.in[[3]]$se.m.2.2),
            mean(data.in[[3]]$se.m.2.3),
            mean(data.in[[3]]$se.m.2.4),
            mean(data.in[[3]]$se.m.2.5),
            mean(data.in[[3]]$se.m.2.6)),3),
    round(c(mean(data.in[[3]]$se.dl.1.1),
            mean(data.in[[3]]$se.dl.1.2),
            mean(data.in[[3]]$se.dl.1.3),
            mean(data.in[[3]]$se.dl.1.4),
            mean(data.in[[3]]$se.dl.1.5),
            mean(data.in[[3]]$se.dl.1.6),
            mean(data.in[[3]]$se.dl.2.1),
            mean(data.in[[3]]$se.dl.2.2),
            mean(data.in[[3]]$se.dl.2.3),
            mean(data.in[[3]]$se.dl.2.4),
            mean(data.in[[3]]$se.dl.2.5),
            mean(data.in[[3]]$se.dl.2.6)),3),
    # Fourth row
    round(c(mean(data.in[[4]]$se.m.1.1),
            mean(data.in[[4]]$se.m.1.2),
            mean(data.in[[4]]$se.m.1.3),
            mean(data.in[[4]]$se.m.1.4),
            mean(data.in[[4]]$se.m.1.5),
            mean(data.in[[4]]$se.m.1.6),
            mean(data.in[[4]]$se.m.2.1),
            mean(data.in[[4]]$se.m.2.2),
            mean(data.in[[4]]$se.m.2.3),
            mean(data.in[[4]]$se.m.2.4),
            mean(data.in[[4]]$se.m.2.5),
            mean(data.in[[4]]$se.m.2.6)),3),
    round(c(mean(data.in[[4]]$se.dl.1.1),
            mean(data.in[[4]]$se.dl.1.2),
            mean(data.in[[4]]$se.dl.1.3),
            mean(data.in[[4]]$se.dl.1.4),
            mean(data.in[[4]]$se.dl.1.5),
            mean(data.in[[4]]$se.dl.1.6),
            mean(data.in[[4]]$se.dl.2.1),
            mean(data.in[[4]]$se.dl.2.2),
            mean(data.in[[4]]$se.dl.2.3),
            mean(data.in[[4]]$se.dl.2.4),
            mean(data.in[[4]]$se.dl.2.5),
            mean(data.in[[4]]$se.dl.2.6)),3),
    # Fifth row
    round(c(mean(data.in[[5]]$se.m.1.1),
            mean(data.in[[5]]$se.m.1.2),
            mean(data.in[[5]]$se.m.1.3),
            mean(data.in[[5]]$se.m.1.4),
            mean(data.in[[5]]$se.m.1.5),
            mean(data.in[[5]]$se.m.1.6),
            mean(data.in[[5]]$se.m.2.1),
            mean(data.in[[5]]$se.m.2.2),
            mean(data.in[[5]]$se.m.2.3),
            mean(data.in[[5]]$se.m.2.4),
            mean(data.in[[5]]$se.m.2.5),
            mean(data.in[[5]]$se.m.2.6)),3),
    round(c(mean(data.in[[5]]$se.dl.1.1),
            mean(data.in[[5]]$se.dl.1.2),
            mean(data.in[[5]]$se.dl.1.3),
            mean(data.in[[5]]$se.dl.1.4),
            mean(data.in[[5]]$se.dl.1.5),
            mean(data.in[[5]]$se.dl.1.6),
            mean(data.in[[5]]$se.dl.2.1),
            mean(data.in[[5]]$se.dl.2.2),
            mean(data.in[[5]]$se.dl.2.3),
            mean(data.in[[5]]$se.dl.2.4),
            mean(data.in[[5]]$se.dl.2.5),
            mean(data.in[[5]]$se.dl.2.6)),3),
    # Sixth row
    round(c(mean(data.in[[6]]$se.m.1.1),
            mean(data.in[[6]]$se.m.1.2),
            mean(data.in[[6]]$se.m.1.3),
            mean(data.in[[6]]$se.m.1.4),
            mean(data.in[[6]]$se.m.1.5),
            mean(data.in[[6]]$se.m.1.6),
            mean(data.in[[6]]$se.m.2.1),
            mean(data.in[[6]]$se.m.2.2),
            mean(data.in[[6]]$se.m.2.3),
            mean(data.in[[6]]$se.m.2.4),
            mean(data.in[[6]]$se.m.2.5),
            mean(data.in[[6]]$se.m.2.6)),3),
    round(c(mean(data.in[[6]]$se.dl.1.1),
            mean(data.in[[6]]$se.dl.1.2),
            mean(data.in[[6]]$se.dl.1.3),
            mean(data.in[[6]]$se.dl.1.4),
            mean(data.in[[6]]$se.dl.1.5),
            mean(data.in[[6]]$se.dl.1.6),
            mean(data.in[[6]]$se.dl.2.1),
            mean(data.in[[6]]$se.dl.2.2),
            mean(data.in[[6]]$se.dl.2.3),
            mean(data.in[[6]]$se.dl.2.4),
            mean(data.in[[6]]$se.dl.2.5),
            mean(data.in[[6]]$se.dl.2.6)),3),
    # Seventh row
    round(c(mean(data.in[[7]]$se.m.1.1),
            mean(data.in[[7]]$se.m.1.2),
            mean(data.in[[7]]$se.m.1.3),
            mean(data.in[[7]]$se.m.1.4),
            mean(data.in[[7]]$se.m.1.5),
            mean(data.in[[7]]$se.m.1.6),
            mean(data.in[[7]]$se.m.2.1),
            mean(data.in[[7]]$se.m.2.2),
            mean(data.in[[7]]$se.m.2.3),
            mean(data.in[[7]]$se.m.2.4),
            mean(data.in[[7]]$se.m.2.5),
            mean(data.in[[7]]$se.m.2.6)),3),
    round(c(mean(data.in[[7]]$se.dl.1.1),
            mean(data.in[[7]]$se.dl.1.2),
            mean(data.in[[7]]$se.dl.1.3),
            mean(data.in[[7]]$se.dl.1.4),
            mean(data.in[[7]]$se.dl.1.5),
            mean(data.in[[7]]$se.dl.1.6),
            mean(data.in[[7]]$se.dl.2.1),
            mean(data.in[[7]]$se.dl.2.2),
            mean(data.in[[7]]$se.dl.2.3),
            mean(data.in[[7]]$se.dl.2.4),
            mean(data.in[[7]]$se.dl.2.5),
            mean(data.in[[7]]$se.dl.2.6)),3)
  )
  return(tables.out)}


get.output.tables.se.mean.i6 <- function(data.in){
  tables.out <- rbind(
    # First row
    round(c(mean(data.in[[1]]$se.m.1.1),
            mean(data.in[[1]]$se.m.1.2),
            mean(data.in[[1]]$se.m.1.3),
            mean(data.in[[1]]$se.m.1.4),
            mean(data.in[[1]]$se.m.1.5),
            mean(data.in[[1]]$se.m.1.6),
            mean(data.in[[1]]$se.m.2.1),
            mean(data.in[[1]]$se.m.2.2),
            mean(data.in[[1]]$se.m.2.3),
            mean(data.in[[1]]$se.m.2.4),
            mean(data.in[[1]]$se.m.2.5),
            mean(data.in[[1]]$se.m.2.6)),3),
    round(c(mean(data.in[[1]]$se.dl.1.1),
            mean(data.in[[1]]$se.dl.1.2),
            mean(data.in[[1]]$se.dl.1.3),
            mean(data.in[[1]]$se.dl.1.4),
            mean(data.in[[1]]$se.dl.1.5),
            mean(data.in[[1]]$se.dl.1.6),
            mean(data.in[[1]]$se.dl.2.1),
            mean(data.in[[1]]$se.dl.2.2),
            mean(data.in[[1]]$se.dl.2.3),
            mean(data.in[[1]]$se.dl.2.4),
            mean(data.in[[1]]$se.dl.2.5),
            mean(data.in[[1]]$se.dl.2.6)),3),
    # Second row
    round(c(mean(data.in[[2]]$se.m.1.1),
            mean(data.in[[2]]$se.m.1.2),
            mean(data.in[[2]]$se.m.1.3),
            mean(data.in[[2]]$se.m.1.4),
            mean(data.in[[2]]$se.m.1.5),
            mean(data.in[[2]]$se.m.1.6),
            mean(data.in[[2]]$se.m.2.1),
            mean(data.in[[2]]$se.m.2.2),
            mean(data.in[[2]]$se.m.2.3),
            mean(data.in[[2]]$se.m.2.4),
            mean(data.in[[2]]$se.m.2.5),
            mean(data.in[[2]]$se.m.2.6)),3),
    round(c(mean(data.in[[2]]$se.dl.1.1),
            mean(data.in[[2]]$se.dl.1.2),
            mean(data.in[[2]]$se.dl.1.3),
            mean(data.in[[2]]$se.dl.1.4),
            mean(data.in[[2]]$se.dl.1.5),
            mean(data.in[[2]]$se.dl.1.6),
            mean(data.in[[2]]$se.dl.2.1),
            mean(data.in[[2]]$se.dl.2.2),
            mean(data.in[[2]]$se.dl.2.3),
            mean(data.in[[2]]$se.dl.2.4),
            mean(data.in[[2]]$se.dl.2.5),
            mean(data.in[[2]]$se.dl.2.6)),3),
    # Third row
    round(c(mean(data.in[[3]]$se.m.1.1),
            mean(data.in[[3]]$se.m.1.2),
            mean(data.in[[3]]$se.m.1.3),
            mean(data.in[[3]]$se.m.1.4),
            mean(data.in[[3]]$se.m.1.5),
            mean(data.in[[3]]$se.m.1.6),
            mean(data.in[[3]]$se.m.2.1),
            mean(data.in[[3]]$se.m.2.2),
            mean(data.in[[3]]$se.m.2.3),
            mean(data.in[[3]]$se.m.2.4),
            mean(data.in[[3]]$se.m.2.5),
            mean(data.in[[3]]$se.m.2.6)),3),
    round(c(mean(data.in[[3]]$se.dl.1.1),
            mean(data.in[[3]]$se.dl.1.2),
            mean(data.in[[3]]$se.dl.1.3),
            mean(data.in[[3]]$se.dl.1.4),
            mean(data.in[[3]]$se.dl.1.5),
            mean(data.in[[3]]$se.dl.1.6),
            mean(data.in[[3]]$se.dl.2.1),
            mean(data.in[[3]]$se.dl.2.2),
            mean(data.in[[3]]$se.dl.2.3),
            mean(data.in[[3]]$se.dl.2.4),
            mean(data.in[[3]]$se.dl.2.5),
            mean(data.in[[3]]$se.dl.2.6)),3),
    # Fourth row
    round(c(mean(data.in[[4]]$se.m.1.1),
            mean(data.in[[4]]$se.m.1.2),
            mean(data.in[[4]]$se.m.1.3),
            mean(data.in[[4]]$se.m.1.4),
            mean(data.in[[4]]$se.m.1.5),
            mean(data.in[[4]]$se.m.1.6),
            mean(data.in[[4]]$se.m.2.1),
            mean(data.in[[4]]$se.m.2.2),
            mean(data.in[[4]]$se.m.2.3),
            mean(data.in[[4]]$se.m.2.4),
            mean(data.in[[4]]$se.m.2.5),
            mean(data.in[[4]]$se.m.2.6)),3),
    round(c(mean(data.in[[4]]$se.dl.1.1),
            mean(data.in[[4]]$se.dl.1.2),
            mean(data.in[[4]]$se.dl.1.3),
            mean(data.in[[4]]$se.dl.1.4),
            mean(data.in[[4]]$se.dl.1.5),
            mean(data.in[[4]]$se.dl.1.6),
            mean(data.in[[4]]$se.dl.2.1),
            mean(data.in[[4]]$se.dl.2.2),
            mean(data.in[[4]]$se.dl.2.3),
            mean(data.in[[4]]$se.dl.2.4),
            mean(data.in[[4]]$se.dl.2.5),
            mean(data.in[[4]]$se.dl.2.6)),3),
    # Fifth row
    round(c(mean(data.in[[5]]$se.m.1.1),
            mean(data.in[[5]]$se.m.1.2),
            mean(data.in[[5]]$se.m.1.3),
            mean(data.in[[5]]$se.m.1.4),
            mean(data.in[[5]]$se.m.1.5),
            mean(data.in[[5]]$se.m.1.6),
            mean(data.in[[5]]$se.m.2.1),
            mean(data.in[[5]]$se.m.2.2),
            mean(data.in[[5]]$se.m.2.3),
            mean(data.in[[5]]$se.m.2.4),
            mean(data.in[[5]]$se.m.2.5),
            mean(data.in[[5]]$se.m.2.6)),3),
    round(c(mean(data.in[[5]]$se.dl.1.1),
            mean(data.in[[5]]$se.dl.1.2),
            mean(data.in[[5]]$se.dl.1.3),
            mean(data.in[[5]]$se.dl.1.4),
            mean(data.in[[5]]$se.dl.1.5),
            mean(data.in[[5]]$se.dl.1.6),
            mean(data.in[[5]]$se.dl.2.1),
            mean(data.in[[5]]$se.dl.2.2),
            mean(data.in[[5]]$se.dl.2.3),
            mean(data.in[[5]]$se.dl.2.4),
            mean(data.in[[5]]$se.dl.2.5),
            mean(data.in[[5]]$se.dl.2.6)),3),
    # Sixth row
    round(c(mean(data.in[[6]]$se.m.1.1),
            mean(data.in[[6]]$se.m.1.2),
            mean(data.in[[6]]$se.m.1.3),
            mean(data.in[[6]]$se.m.1.4),
            mean(data.in[[6]]$se.m.1.5),
            mean(data.in[[6]]$se.m.1.6),
            mean(data.in[[6]]$se.m.2.1),
            mean(data.in[[6]]$se.m.2.2),
            mean(data.in[[6]]$se.m.2.3),
            mean(data.in[[6]]$se.m.2.4),
            mean(data.in[[6]]$se.m.2.5),
            mean(data.in[[6]]$se.m.2.6)),3),
    round(c(mean(data.in[[6]]$se.dl.1.1),
            mean(data.in[[6]]$se.dl.1.2),
            mean(data.in[[6]]$se.dl.1.3),
            mean(data.in[[6]]$se.dl.1.4),
            mean(data.in[[6]]$se.dl.1.5),
            mean(data.in[[6]]$se.dl.1.6),
            mean(data.in[[6]]$se.dl.2.1),
            mean(data.in[[6]]$se.dl.2.2),
            mean(data.in[[6]]$se.dl.2.3),
            mean(data.in[[6]]$se.dl.2.4),
            mean(data.in[[6]]$se.dl.2.5),
            mean(data.in[[6]]$se.dl.2.6)),3)
  )
  return(tables.out)}


### Calculate median of each entity of interest and put into a table
get.output.tables.se.median <- function(data.in){
  tables.out <- rbind(
    # First row
    round(c(median(data.in[[1]]$se.m.1.1),
            median(data.in[[1]]$se.m.1.2),
            median(data.in[[1]]$se.m.1.3),
            median(data.in[[1]]$se.m.1.4),
            median(data.in[[1]]$se.m.1.5),
            median(data.in[[1]]$se.m.1.6),
            median(data.in[[1]]$se.m.2.1),
            median(data.in[[1]]$se.m.2.2),
            median(data.in[[1]]$se.m.2.3),
            median(data.in[[1]]$se.m.2.4),
            median(data.in[[1]]$se.m.2.5),
            median(data.in[[1]]$se.m.2.6)),3),
    round(c(median(data.in[[1]]$se.dl.1.1),
            median(data.in[[1]]$se.dl.1.2),
            median(data.in[[1]]$se.dl.1.3),
            median(data.in[[1]]$se.dl.1.4),
            median(data.in[[1]]$se.dl.1.5),
            median(data.in[[1]]$se.dl.1.6),
            median(data.in[[1]]$se.dl.2.1),
            median(data.in[[1]]$se.dl.2.2),
            median(data.in[[1]]$se.dl.2.3),
            median(data.in[[1]]$se.dl.2.4),
            median(data.in[[1]]$se.dl.2.5),
            median(data.in[[1]]$se.dl.2.6)),3),
    # Second row
    round(c(median(data.in[[2]]$se.m.1.1),
            median(data.in[[2]]$se.m.1.2),
            median(data.in[[2]]$se.m.1.3),
            median(data.in[[2]]$se.m.1.4),
            median(data.in[[2]]$se.m.1.5),
            median(data.in[[2]]$se.m.1.6),
            median(data.in[[2]]$se.m.2.1),
            median(data.in[[2]]$se.m.2.2),
            median(data.in[[2]]$se.m.2.3),
            median(data.in[[2]]$se.m.2.4),
            median(data.in[[2]]$se.m.2.5),
            median(data.in[[2]]$se.m.2.6)),3),
    round(c(median(data.in[[2]]$se.dl.1.1),
            median(data.in[[2]]$se.dl.1.2),
            median(data.in[[2]]$se.dl.1.3),
            median(data.in[[2]]$se.dl.1.4),
            median(data.in[[2]]$se.dl.1.5),
            median(data.in[[2]]$se.dl.1.6),
            median(data.in[[2]]$se.dl.2.1),
            median(data.in[[2]]$se.dl.2.2),
            median(data.in[[2]]$se.dl.2.3),
            median(data.in[[2]]$se.dl.2.4),
            median(data.in[[2]]$se.dl.2.5),
            median(data.in[[2]]$se.dl.2.6)),3),
    # Third row
    round(c(median(data.in[[3]]$se.m.1.1),
            median(data.in[[3]]$se.m.1.2),
            median(data.in[[3]]$se.m.1.3),
            median(data.in[[3]]$se.m.1.4),
            median(data.in[[3]]$se.m.1.5),
            median(data.in[[3]]$se.m.1.6),
            median(data.in[[3]]$se.m.2.1),
            median(data.in[[3]]$se.m.2.2),
            median(data.in[[3]]$se.m.2.3),
            median(data.in[[3]]$se.m.2.4),
            median(data.in[[3]]$se.m.2.5),
            median(data.in[[3]]$se.m.2.6)),3),
    round(c(median(data.in[[3]]$se.dl.1.1),
            median(data.in[[3]]$se.dl.1.2),
            median(data.in[[3]]$se.dl.1.3),
            median(data.in[[3]]$se.dl.1.4),
            median(data.in[[3]]$se.dl.1.5),
            median(data.in[[3]]$se.dl.1.6),
            median(data.in[[3]]$se.dl.2.1),
            median(data.in[[3]]$se.dl.2.2),
            median(data.in[[3]]$se.dl.2.3),
            median(data.in[[3]]$se.dl.2.4),
            median(data.in[[3]]$se.dl.2.5),
            median(data.in[[3]]$se.dl.2.6)),3),
    # Fourth row
    round(c(median(data.in[[4]]$se.m.1.1),
            median(data.in[[4]]$se.m.1.2),
            median(data.in[[4]]$se.m.1.3),
            median(data.in[[4]]$se.m.1.4),
            median(data.in[[4]]$se.m.1.5),
            median(data.in[[4]]$se.m.1.6),
            median(data.in[[4]]$se.m.2.1),
            median(data.in[[4]]$se.m.2.2),
            median(data.in[[4]]$se.m.2.3),
            median(data.in[[4]]$se.m.2.4),
            median(data.in[[4]]$se.m.2.5),
            median(data.in[[4]]$se.m.2.6)),3),
    round(c(median(data.in[[4]]$se.dl.1.1),
            median(data.in[[4]]$se.dl.1.2),
            median(data.in[[4]]$se.dl.1.3),
            median(data.in[[4]]$se.dl.1.4),
            median(data.in[[4]]$se.dl.1.5),
            median(data.in[[4]]$se.dl.1.6),
            median(data.in[[4]]$se.dl.2.1),
            median(data.in[[4]]$se.dl.2.2),
            median(data.in[[4]]$se.dl.2.3),
            median(data.in[[4]]$se.dl.2.4),
            median(data.in[[4]]$se.dl.2.5),
            median(data.in[[4]]$se.dl.2.6)),3),
    # Fifth row
    round(c(median(data.in[[5]]$se.m.1.1),
            median(data.in[[5]]$se.m.1.2),
            median(data.in[[5]]$se.m.1.3),
            median(data.in[[5]]$se.m.1.4),
            median(data.in[[5]]$se.m.1.5),
            median(data.in[[5]]$se.m.1.6),
            median(data.in[[5]]$se.m.2.1),
            median(data.in[[5]]$se.m.2.2),
            median(data.in[[5]]$se.m.2.3),
            median(data.in[[5]]$se.m.2.4),
            median(data.in[[5]]$se.m.2.5),
            median(data.in[[5]]$se.m.2.6)),3),
    round(c(median(data.in[[5]]$se.dl.1.1),
            median(data.in[[5]]$se.dl.1.2),
            median(data.in[[5]]$se.dl.1.3),
            median(data.in[[5]]$se.dl.1.4),
            median(data.in[[5]]$se.dl.1.5),
            median(data.in[[5]]$se.dl.1.6),
            median(data.in[[5]]$se.dl.2.1),
            median(data.in[[5]]$se.dl.2.2),
            median(data.in[[5]]$se.dl.2.3),
            median(data.in[[5]]$se.dl.2.4),
            median(data.in[[5]]$se.dl.2.5),
            median(data.in[[5]]$se.dl.2.6)),3),
    # Sixth row
    round(c(median(data.in[[6]]$se.m.1.1),
            median(data.in[[6]]$se.m.1.2),
            median(data.in[[6]]$se.m.1.3),
            median(data.in[[6]]$se.m.1.4),
            median(data.in[[6]]$se.m.1.5),
            median(data.in[[6]]$se.m.1.6),
            median(data.in[[6]]$se.m.2.1),
            median(data.in[[6]]$se.m.2.2),
            median(data.in[[6]]$se.m.2.3),
            median(data.in[[6]]$se.m.2.4),
            median(data.in[[6]]$se.m.2.5),
            median(data.in[[6]]$se.m.2.6)),3),
    round(c(median(data.in[[6]]$se.dl.1.1),
            median(data.in[[6]]$se.dl.1.2),
            median(data.in[[6]]$se.dl.1.3),
            median(data.in[[6]]$se.dl.1.4),
            median(data.in[[6]]$se.dl.1.5),
            median(data.in[[6]]$se.dl.1.6),
            median(data.in[[6]]$se.dl.2.1),
            median(data.in[[6]]$se.dl.2.2),
            median(data.in[[6]]$se.dl.2.3),
            median(data.in[[6]]$se.dl.2.4),
            median(data.in[[6]]$se.dl.2.5),
            median(data.in[[6]]$se.dl.2.6)),3),
    # Seventh row
    round(c(median(data.in[[7]]$se.m.1.1),
            median(data.in[[7]]$se.m.1.2),
            median(data.in[[7]]$se.m.1.3),
            median(data.in[[7]]$se.m.1.4),
            median(data.in[[7]]$se.m.1.5),
            median(data.in[[7]]$se.m.1.6),
            median(data.in[[7]]$se.m.2.1),
            median(data.in[[7]]$se.m.2.2),
            median(data.in[[7]]$se.m.2.3),
            median(data.in[[7]]$se.m.2.4),
            median(data.in[[7]]$se.m.2.5),
            median(data.in[[7]]$se.m.2.6)),3),
    round(c(median(data.in[[7]]$se.dl.1.1),
            median(data.in[[7]]$se.dl.1.2),
            median(data.in[[7]]$se.dl.1.3),
            median(data.in[[7]]$se.dl.1.4),
            median(data.in[[7]]$se.dl.1.5),
            median(data.in[[7]]$se.dl.1.6),
            median(data.in[[7]]$se.dl.2.1),
            median(data.in[[7]]$se.dl.2.2),
            median(data.in[[7]]$se.dl.2.3),
            median(data.in[[7]]$se.dl.2.4),
            median(data.in[[7]]$se.dl.2.5),
            median(data.in[[7]]$se.dl.2.6)),3)
  )
  return(tables.out)}


get.output.tables.se.median.i6 <- function(data.in){
  tables.out <- rbind(
    # First row
    round(c(median(data.in[[1]]$se.m.1.1),
            median(data.in[[1]]$se.m.1.2),
            median(data.in[[1]]$se.m.1.3),
            median(data.in[[1]]$se.m.1.4),
            median(data.in[[1]]$se.m.1.5),
            median(data.in[[1]]$se.m.1.6),
            median(data.in[[1]]$se.m.2.1),
            median(data.in[[1]]$se.m.2.2),
            median(data.in[[1]]$se.m.2.3),
            median(data.in[[1]]$se.m.2.4),
            median(data.in[[1]]$se.m.2.5),
            median(data.in[[1]]$se.m.2.6)),3),
    round(c(median(data.in[[1]]$se.dl.1.1),
            median(data.in[[1]]$se.dl.1.2),
            median(data.in[[1]]$se.dl.1.3),
            median(data.in[[1]]$se.dl.1.4),
            median(data.in[[1]]$se.dl.1.5),
            median(data.in[[1]]$se.dl.1.6),
            median(data.in[[1]]$se.dl.2.1),
            median(data.in[[1]]$se.dl.2.2),
            median(data.in[[1]]$se.dl.2.3),
            median(data.in[[1]]$se.dl.2.4),
            median(data.in[[1]]$se.dl.2.5),
            median(data.in[[1]]$se.dl.2.6)),3),
    # Second row
    round(c(median(data.in[[2]]$se.m.1.1),
            median(data.in[[2]]$se.m.1.2),
            median(data.in[[2]]$se.m.1.3),
            median(data.in[[2]]$se.m.1.4),
            median(data.in[[2]]$se.m.1.5),
            median(data.in[[2]]$se.m.1.6),
            median(data.in[[2]]$se.m.2.1),
            median(data.in[[2]]$se.m.2.2),
            median(data.in[[2]]$se.m.2.3),
            median(data.in[[2]]$se.m.2.4),
            median(data.in[[2]]$se.m.2.5),
            median(data.in[[2]]$se.m.2.6)),3),
    round(c(median(data.in[[2]]$se.dl.1.1),
            median(data.in[[2]]$se.dl.1.2),
            median(data.in[[2]]$se.dl.1.3),
            median(data.in[[2]]$se.dl.1.4),
            median(data.in[[2]]$se.dl.1.5),
            median(data.in[[2]]$se.dl.1.6),
            median(data.in[[2]]$se.dl.2.1),
            median(data.in[[2]]$se.dl.2.2),
            median(data.in[[2]]$se.dl.2.3),
            median(data.in[[2]]$se.dl.2.4),
            median(data.in[[2]]$se.dl.2.5),
            median(data.in[[2]]$se.dl.2.6)),3),
    # Third row
    round(c(median(data.in[[3]]$se.m.1.1),
            median(data.in[[3]]$se.m.1.2),
            median(data.in[[3]]$se.m.1.3),
            median(data.in[[3]]$se.m.1.4),
            median(data.in[[3]]$se.m.1.5),
            median(data.in[[3]]$se.m.1.6),
            median(data.in[[3]]$se.m.2.1),
            median(data.in[[3]]$se.m.2.2),
            median(data.in[[3]]$se.m.2.3),
            median(data.in[[3]]$se.m.2.4),
            median(data.in[[3]]$se.m.2.5),
            median(data.in[[3]]$se.m.2.6)),3),
    round(c(median(data.in[[3]]$se.dl.1.1),
            median(data.in[[3]]$se.dl.1.2),
            median(data.in[[3]]$se.dl.1.3),
            median(data.in[[3]]$se.dl.1.4),
            median(data.in[[3]]$se.dl.1.5),
            median(data.in[[3]]$se.dl.1.6),
            median(data.in[[3]]$se.dl.2.1),
            median(data.in[[3]]$se.dl.2.2),
            median(data.in[[3]]$se.dl.2.3),
            median(data.in[[3]]$se.dl.2.4),
            median(data.in[[3]]$se.dl.2.5),
            median(data.in[[3]]$se.dl.2.6)),3),
    # Fourth row
    round(c(median(data.in[[4]]$se.m.1.1),
            median(data.in[[4]]$se.m.1.2),
            median(data.in[[4]]$se.m.1.3),
            median(data.in[[4]]$se.m.1.4),
            median(data.in[[4]]$se.m.1.5),
            median(data.in[[4]]$se.m.1.6),
            median(data.in[[4]]$se.m.2.1),
            median(data.in[[4]]$se.m.2.2),
            median(data.in[[4]]$se.m.2.3),
            median(data.in[[4]]$se.m.2.4),
            median(data.in[[4]]$se.m.2.5),
            median(data.in[[4]]$se.m.2.6)),3),
    round(c(median(data.in[[4]]$se.dl.1.1),
            median(data.in[[4]]$se.dl.1.2),
            median(data.in[[4]]$se.dl.1.3),
            median(data.in[[4]]$se.dl.1.4),
            median(data.in[[4]]$se.dl.1.5),
            median(data.in[[4]]$se.dl.1.6),
            median(data.in[[4]]$se.dl.2.1),
            median(data.in[[4]]$se.dl.2.2),
            median(data.in[[4]]$se.dl.2.3),
            median(data.in[[4]]$se.dl.2.4),
            median(data.in[[4]]$se.dl.2.5),
            median(data.in[[4]]$se.dl.2.6)),3),
    # Fifth row
    round(c(median(data.in[[5]]$se.m.1.1),
            median(data.in[[5]]$se.m.1.2),
            median(data.in[[5]]$se.m.1.3),
            median(data.in[[5]]$se.m.1.4),
            median(data.in[[5]]$se.m.1.5),
            median(data.in[[5]]$se.m.1.6),
            median(data.in[[5]]$se.m.2.1),
            median(data.in[[5]]$se.m.2.2),
            median(data.in[[5]]$se.m.2.3),
            median(data.in[[5]]$se.m.2.4),
            median(data.in[[5]]$se.m.2.5),
            median(data.in[[5]]$se.m.2.6)),3),
    round(c(median(data.in[[5]]$se.dl.1.1),
            median(data.in[[5]]$se.dl.1.2),
            median(data.in[[5]]$se.dl.1.3),
            median(data.in[[5]]$se.dl.1.4),
            median(data.in[[5]]$se.dl.1.5),
            median(data.in[[5]]$se.dl.1.6),
            median(data.in[[5]]$se.dl.2.1),
            median(data.in[[5]]$se.dl.2.2),
            median(data.in[[5]]$se.dl.2.3),
            median(data.in[[5]]$se.dl.2.4),
            median(data.in[[5]]$se.dl.2.5),
            median(data.in[[5]]$se.dl.2.6)),3),
    # Sixth row
    round(c(median(data.in[[6]]$se.m.1.1),
            median(data.in[[6]]$se.m.1.2),
            median(data.in[[6]]$se.m.1.3),
            median(data.in[[6]]$se.m.1.4),
            median(data.in[[6]]$se.m.1.5),
            median(data.in[[6]]$se.m.1.6),
            median(data.in[[6]]$se.m.2.1),
            median(data.in[[6]]$se.m.2.2),
            median(data.in[[6]]$se.m.2.3),
            median(data.in[[6]]$se.m.2.4),
            median(data.in[[6]]$se.m.2.5),
            median(data.in[[6]]$se.m.2.6)),3),
    round(c(median(data.in[[6]]$se.dl.1.1),
            median(data.in[[6]]$se.dl.1.2),
            median(data.in[[6]]$se.dl.1.3),
            median(data.in[[6]]$se.dl.1.4),
            median(data.in[[6]]$se.dl.1.5),
            median(data.in[[6]]$se.dl.1.6),
            median(data.in[[6]]$se.dl.2.1),
            median(data.in[[6]]$se.dl.2.2),
            median(data.in[[6]]$se.dl.2.3),
            median(data.in[[6]]$se.dl.2.4),
            median(data.in[[6]]$se.dl.2.5),
            median(data.in[[6]]$se.dl.2.6)),3)
  )
  return(tables.out)}



### And apply it to each set of results
output.se.scen1.mean <- get.output.tables.se.mean(scen1.dataframes.S)
output.se.scen2.mean <- get.output.tables.se.mean(scen2.dataframes.S)
output.se.scen3.mean <- get.output.tables.se.mean(scen3.dataframes.S)
output.se.scen4.mean <- get.output.tables.se.mean.i6(scen4.dataframes.S)
output.se.scen5.mean <- get.output.tables.se.mean.i6(scen5.dataframes.S)

output.se.scen1.median <- get.output.tables.se.median(scen1.dataframes.S)
output.se.scen2.median <- get.output.tables.se.median(scen2.dataframes.S)
output.se.scen3.median <- get.output.tables.se.median(scen3.dataframes.S)
output.se.scen4.median <- get.output.tables.se.median.i6(scen4.dataframes.S)
output.se.scen5.median <- get.output.tables.se.median.i6(scen5.dataframes.S)

save.image("R_out/multinom dl comparison results scen1to5.RData")
